name: test_workflow
on:
  push:
  pull_request:
    branches: 'main'

jobs:
  commit-check:
    runs-on: ubuntu-latest
    steps:
    - name: Set current date as env variable
      run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
    - name: Checkout
      uses: actions/checkout@v3
    - name: Test deadcode
      uses: ahmet/go-deadcode-checker@v1
    - uses: snow-actions/line-notify@v1.1.0
      with:
        access_token: ${{ secrets.LINE_ACCESS_TOKEN }}
        message: |
          Notification
          Repository: ${{ github.repository }}
          Workflow: ${{ github.workflow }}
          Workflow Run ID: ${{ github.run_id }}
          Timestamp: ${{ env.NOW }}
